openapi: 3.0.3
info:
  title: Goodreads ChoiceAward API
  description: |-
    This API provides comprehensive access to the nominees of the Goodreads Choice Awards from 2019 to 2023. Each year, Goodreads hosts these prestigious awards, allowing readers worldwide to vote for their favorite books across various categories. Our API offers detailed insights into each award category, including a list of books that won and those that were nominated.

    * [Goodreads ChoiceAward](https://www.goodreads.com/choiceawards/best-books-2023) 
    
    This API is ideal for researchers, book reviewers, and any application where literary trends and preferences are analyzed. Access to this rich dataset empowers developers to build applications that engage book enthusiasts and support reading communities with up-to-date and historical award data.
    * more information about [GoodReads](https://www.goodreads.com//)
  contact:
    email: xiaobo.teng93@gmail.com
  license:
    name: CC BY-NC 3.0
    url: https://creativecommons.org/licenses/by-nc/3.0/
  version: 1.0.0
servers:
- url: /
paths:
  /v1/awardslist:
    get:
      tags: 
        - Search for the lists of ChoiceAwards
      summary: Retrieve all the lists of ChoiceAwards from 2019 to 2023
      description: Return all the information about all the lists of awards
      parameters:
        - name: page
          in: query
          example: 1
          description: Index of the page (used for pagination)
          schema:
            type: integer
        - name: page_size
          in: query
          example: 30
          description: Number of games per page (used for pagination)
          schema:
            type: integer
        - name: include_details
          in: query
          example: 0
          description: Whether or not to display more_info (0 or 1)
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  movies:
                    type: array
                    items:
                      $ref: '#/components/schemas/Award'
                  next_page:
                    type: integer
                    example: 1
                  last_page:
                    type: integer
                    example: 903
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      security:
        - api_auth: []
        
  /v1/awardslist/{year}:
    get:
      tags: 
        - Search for the lists of ChoiceAwards
      summary: Access list of award of one year
      description: Return all the information about list
      parameters:
        - name: year
          in: path
          description: the year you want the list
          example: 2023
          required: true
          schema:
            type: string
        - name: include_details
          in: query
          example: 0
          description: Whether or not to display more_info (0 or 1)
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Award'          
        '404':
          description: Book not found
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      security:
        - api_auth: []
        
  /v1/books:
    get:
      tags: 
        - Search for list of books
      summary: Retrieve all nommies of best books from 2019 to 2023
      description: Return all the information about all the books
      parameters:
        - name: page
          in: query
          example: 1
          description: Index of the page (used for pagination)
          schema:
            type: integer
        - name: page_size
          in: query
          example: 30
          description: Number of games per page (used for pagination)
          schema:
            type: integer
        - name: include_details
          in: query
          example: 0
          description: Whether or not to display more_info (0 or 1)
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  movies:
                    type: array
                    items:
                      $ref: '#/components/schemas/Book'
                  next_page:
                    type: integer
                    example: 1
                  last_page:
                    type: integer
                    example: 903
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      security:
        - api_auth: []  
        
  /v1/books/{title_id}:
    get:
      tags: 
        - Search for a book
      summary: Access detailed information for each book, including author, publication details, genre, ratings, award, votes and description
      description: Return all the information about a game
      parameters:
        - name: title_id
          in: path
          description: id of the book
          example: 111
          required: true
          schema:
            type: string
        - name: include_details
          in: query
          example: 0
          description: Whether or not to display more_info (0 or 1)
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'          
        '404':
          description: Book not found
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      security:
        - api_auth: []


components:
  schemas:
    Award:
      required:
        - award_id
      type: object
      properties:
        award_id:
          type: integer
          example: 1
        award:
          type: string
          example: best-fiction-books-2023
        books:
          type: array
          description: list of nommies
          items:
            $ref: '#/components/schemas/Books'
            
    Book:
      required:
        - title_id
      type: object
      properties:
        title_id:
          type: integer
          example: 111
        title:
          type: string
          example: Five Feet Apart
        publish_date:
          type: string
          format: date
          example: 2018-11-20
        author:
          type: string
          example: Frogwares
        award:
          type: string
          example: best-young-adult-fiction-books-201
        genres:
          type: string
          example: Romance, Young Adult, Contemporary, Fiction, Audiobook, Realistic Fiction, Young Adult Romance
        format:
          type: string
          example: Hardcover
        pages:
          type: integer
          example: 304.0
        rating:
          type: integer
          example: 4.18
        more_info:
          type: array
          description: description of the story
          items:
            $ref: '#/components/schemas/More_info'
    Books:
      required:
        - appid
      type: object
      properties:
        award_id:
          type: integer
          example: 1
        author:
          type: string
          example: Jojo Moyes
        title:
          type: string
          example: Someone Else's Shoes
        title_id:
          type: integer
          example: 2561
          
    More_info:
      required:
        - title_id
      type: object
      properties:
        description:
          type: string
          description: description of book
          example: Can you love someone you can never touch?
          
  securitySchemes:
    api_auth:
      type: http
      scheme: basic
      description: Please authenticate to use the API